static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: chat_service
                            timeout: 0s
                http_filters:
                  # CORS фильтр должен быть первым
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                      policy:  # Поле policy ВНУТРИ typed_config
                        allow_origin_string_match:
                          - prefix: "*"  # Разрешить все origins (только для тестирования)
                        allow_methods: GET POST PUT DELETE OPTIONS
                        allow_headers: "content-type, authorization, x-grpc-web"
                        allow_credentials: true
                        max_age: "3600"
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.router

  clusters:
    - name: chat_service
      connect_timeout: 0.25s
      type: STRICT_DNS  # Для Docker
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: chat_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: chat-service  # Имя сервиса из docker-compose
                      port_value: 80        # Порт вашего gRPC-сервиса

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901