admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          http2_protocol_options:
            initial_stream_window_size: 65536  # Увеличиваем размер окна для потоков
            initial_connection_window_size: 1048576  # Увеличиваем размер окна для соединений
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: chat_service }
          http_filters:
          - name: envoy.grpc_web
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: chat_service
    connect_timeout: 5s  # Увеличиваем таймаут подключения
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options:
      initial_stream_window_size: 65536  # Увеличиваем размер окна для потоков
      initial_connection_window_size: 1048576  # Увеличиваем размер окна для соединений
    load_assignment:
      cluster_name: chat_service
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: chat-service
                  port_value: 81