services:
  chat-service:
    build:
      context: .
      dockerfile: Chat.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      JwtOptions__Secret: "some_secret_key_HAFHSDHASHDASHDHADHADHASDHADHLOLLOLOLROFLLMAODOTNET"
      JwtOptions__Issuer: "http://localhost:80"
      JwtOptions__Audience: "https://localhost:80"
      JwtOptions__AccessTokenLifetimeMinutes: 60
      DbConnectionString: "User ID=postgres;Password=root;Host=postgres-db;Port=5432;Database=data"
      Kestrel__EndpointsDefault__Protocols: "Http2"
    ports:
      - "80:80"
      - "81:81"

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  envoy:
    build: Envoy/
    ports:
      - "10000:10000"
      - "9901:9901"
      - "10001:10001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
        
volumes:
  postgres_data:
