# This is a generated file. Not intended for manual editing.
services:
  chat-service:
    build:
      context: "/Users/ivansosorin/My/CSharp/Stud/HT.ITIS-3.2/Tasks/GrpcTasks"
      dockerfile: "Chat.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Chat.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "chat.api:dev"
    ports: []
    volumes:
    - "/Users/ivansosorin/My/CSharp/Stud/HT.ITIS-3.2/Tasks/GrpcTasks/Chat.API:/app:rw"
    - "/Users/ivansosorin/My/CSharp/Stud/HT.ITIS-3.2/Tasks/GrpcTasks:/src:rw"
    - "/Users/ivansosorin/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
